name: "always fail"

on:
  pull_request:
  issue_comment:
    types: [created]

name: "Always fail"

jobs:
  no-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Fail PR if after 21:00 CET
        run: 
          exit 1
